const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const path = require('path');
const http = require('http');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const app = express();
const server = http.createServer(app);

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: ['https://communicator.surecloudvoice.com', 'http://localhost:3000', 'http://localhost:5173', 'file://'], credentials: true }));
app.use(express.json({ limit: '10mb' }));

app.use('/api/auth', require('./routes/auth'));
app.use('/api/admin/auth', require('./routes/admin-auth'));
app.use('/api/provision', require('./routes/provision'));
app.use('/api/admin/tenants', require('./routes/admin-tenants'));
app.use('/api/admin/orgs', require('./routes/admin-orgs'));
app.use('/api/admin/users', require('./routes/admin-users'));
app.use('/api/admin/sip', require('./routes/admin-sip'));
app.use('/api/admin/downloads', require('./routes/admin-downloads'));
app.use('/api/admin/upload', require('./routes/admin-upload'));
app.use('/api/admin/fpbx', require('./routes/admin-fpbx'));
app.use('/api/admin/email', require('./routes/admin-email'));
app.use('/api/admin/devices', require('./routes/admin-devices'));
app.use('/api/admin/versions', require('./routes/admin-versions'));
app.use('/api/admin/diagnostics', require('./routes/admin-diagnostics'));
app.use('/api/admin/user-settings', require('./routes/admin-user-settings'));
app.use('/api/app/versions', require('./routes/admin-versions'));
app.use('/api/users', require('./routes/user-directory'));
app.use('/api/conversations', require('./routes/conversations'));
app.use('/api/speed-dials', require('./routes/speed-dials'));
app.use('/api/contacts', require('./routes/fpbx-contacts'));
app.use('/api/call-forward', require('./routes/call-forward'));
app.use('/api/chat-upload', require('./routes/chat-upload'));
app.use('/chat-uploads', express.static(require('path').join(__dirname, '..', 'chat-uploads')));
app.use('/api/transcriptions', require('./routes/transcriptions'));

app.use(express.static(path.join(__dirname, '..', 'public')));
app.use('/downloads', express.static(path.join(__dirname, '..', 'downloads')));

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', service: 'SureCloudVoice Provisioning', version: '2.1.0' });
});

const rawParser = express.raw({ type: '*/*', limit: '5mb' });

// Network diagnostics email
app.post('/api/diagnostics/email', async (req, res) => {
  try {
    const { to_email, report_text, report_html } = req.body;
    if (!to_email || !report_text) return res.status(400).json({ error: 'to_email and report_text required' });
    const { sendEmail } = require('./email');

    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:'Segoe UI',-apple-system,sans-serif;background:#f4f4f5">
  <div style="max-width:640px;margin:0 auto;padding:40px 20px">
    <div style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)">
      <div style="background:#202A44;padding:24px 32px;text-align:center">
        <img src="https://communicator.surecloudvoice.com/img/logo-horizontal.png" alt="SureCloudVoice" style="height:32px;filter:brightness(0) invert(1)">
      </div>
      <div style="padding:32px">
        <h1 style="margin:0 0 4px;font-size:20px;color:#18181b;font-weight:600">Network Diagnostics Report</h1>
        <p style="color:#a1a1aa;font-size:12px;margin:0 0 24px">${report_html ? '' : 'Generated by SureCloudVoice App'}</p>
        ${report_html || '<pre style="background:#f4f4f5;border-radius:8px;padding:20px;font-size:13px;line-height:1.7;color:#27272a;overflow-x:auto;white-space:pre-wrap">' + report_text.replace(/</g, '&lt;').replace(/>/g, '&gt;') + '</pre>'}
      </div>
      <div style="background:#f9fafb;padding:16px 32px;border-top:1px solid #e4e4e7;text-align:center">
        <p style="color:#a1a1aa;font-size:11px;margin:0">SureCloudVoice by Sure &copy; 2026</p>
      </div>
    </div>
  </div>
</body>
</html>`;

    await sendEmail(to_email, 'SureCloudVoice Network Diagnostics Report', html, report_text);
    res.json({ ok: true });
  } catch (err) {
    console.error('Diagnostics email error:', err);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/speedtest/upload', rawParser, (req, res) => {
  res.json({ received: req.body ? req.body.length : 0, ok: true });
});

app.get('/download', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'public', 'download.html'));
});

const adminHtml = path.join(__dirname, '..', 'public', 'index.html');
app.use('/admin', (req, res) => {
  const fs = require('fs');
  if (fs.existsSync(adminHtml)) res.sendFile(adminHtml);
  else res.json({ message: 'Admin portal not deployed' });
});

const { setupWebSocket } = require('./ws');
setupWebSocket(server);

const PORT = process.env.PORT || 3000;
server.listen(PORT, '0.0.0.0', () => {
  console.log(`SureCloudVoice API v2.1.0 running on port ${PORT}`);
});
